extends:
  - standard
  - prettier

env:
  node: true
  mocha: true

parserOptions:
  # Override eslint-config-standard, which incorrectly sets this to "module",
  # though that setting is only for ES6 modules, not CommonJS modules.
  sourceType: 'script'

rules:
  # Allow unused parameters. In callbacks, removing them seems to obscure
  # what the functions are doing.
  no-unused-vars: ['error', { 'args': 'none' }]

  # These should be disabled by eslint-config-prettier, but are not.
  spaced-comment: 'off'
  standard/object-curly-even-spacing: 'off'
  one-var: 'off'

  no-var: 'error'
  prefer-const: 'error'
  strict: 'error'
  arrow-body-style: ['error', 'as-needed']
  object-shorthand: ['error', 'properties']
  prefer-template: 'error'
  promise/prefer-await-to-then: 'error'
